### ISSUE TITLE
dnslib.dns.DNSError: Error unpacking DNSQuestion

### ISSUE THREAD

**Issue by tomagoes** [Arno0x/DNSExfiltrator#7]
I keep getting:

"Traceback (most recent call last):
  File "./dnsexfiltrator.py", line 144, in <module>
    request = DNSRecord.parse(data)
  File "/usr/lib/python2.7/dist-packages/dnslib/dns.py", line 104, in parse
    questions.append(DNSQuestion.parse(buffer))
  File "/usr/lib/python2.7/dist-packages/dnslib/dns.py", line 645, in parse
    buffer.offset,e))
dnslib.dns.DNSError: Error unpacking DNSQuestion [offset=55]: Invalid label <┬álets>"

Any idea how to fix?

**Comment by tomagoes** [comment]
ending up being an extra space in the client command
